### ISSUE TITLE
Unsure how to add the soap package to NextCloud AIO

### ISSUE THREAD

**Issue by JSChasle** [ksainc/integration_ews#24] opened 2023-11-21 19:42 UTC
I tried adding your module and getting the error: The library soap is not available. 

I am using Nextcloud AIO and have check the https://pecl.php.net/packages.php to search for the SOAP package and then I could add it to:  my master container using the reference:

https://github.com/nextcloud/all-in-one#how-to-add-php-extensions-permanently-to-the-nextcloud-container

but since the the soap package does not exist in pecl.php.net I was wondering if I am looking in the wrong place or not trying to use the right package?

Thanks,

**Comment by ksainc** [comment] 2023-11-21 19:45
Hi,

Have a look at Issue #21 read the last comment from me. The instructions are there.

Sebastian

**Comment by ksainc** [comment] 2023-11-21 19:46
Duplicate of #21

**Closed by ksainc** 2023-11-21 19:46 UTC

**Comment by szaimen** [comment] 2023-11-22 15:17
Hi, see https://github.com/nextcloud/all-in-one#how-to-add-php-extensions-permanently-to-the-nextcloud-container

**Comment by cap-blackbeard** [comment] 2025-06-13 06:11
@szaimen 
But what should be done if the extension `soap` is not listed at https://pecl.php.net/packages.php?
