### ISSUE TITLE
Failed to authenticate with EWS server: null

### ISSUE THREAD

**Issue by Mer0me** [ksainc/integration_ews#22] opened 2023-11-15 15:54 UTC
**Describe the bug**
Cannot connect to Exchange 2007 Web Services

**To Reproduce**
1. Fill the fields : 
Account ID : myuser
Account Secret : mypassword
Account Server : https://exchsrv.domain.local/EWS/Exchange.asmx

2. Click Connect 
3. See error

**Expected behavior**
The connection should work

**Desktop (please complete the following information):**
 - OS: Debian
 - Browser Firefox
 - Version 115.4.0esr

**Additional context**
I'm not sure of the EWS URL I should use. Only the FQFN ? With /EWS/Exchange.asmx or not ? It's a self signed certificate, maybe it's the problem ?

**Comment by Mer0me** [comment] 2023-11-15 18:52
I've disable the SSL Check but no more success. "Failed to authenticate with EWS server: null" 
I've tried IP adress, internal and external FQDN, domain\user or user or user@domaine.com ... Nothing works :( 
Any clue ?

**Comment by ksainc** [comment] 2023-11-15 23:43
Okay, from the error message, I believe that the issue is AutoDiscover. I've had a few problems with this in different versions of exchange. This been tested with 2013/2019/Exchange 365 but every version seems to send a slightly different AutoDiscover file.

A) can make sure that your exchange server is accessible from your NC.
B) make sure the "Configure Mail App" option is off
C) make sure the "Configure Server Manually" option is on
D) Enter the username "user@domail.com", enter password and enter IP or internal domain for the server

If this still fails, please send me the error from the NC log.

Sebastian

**Comment by Mer0me** [comment] 2023-11-16 10:10
Thank you for your efforts. We have progressed a little bit.
I've figured out that this old Exchange server was using a very old TLS version that wasn't supported by the NC server. I've modified the last 2 lines of the openssl.cnf of the NC server like this :

```
MinProtocol = TLSv1
CipherString = DEFAULT@SECLEVEL=1
```

Now, I can browse the exchange server manually from the NC server, after accepting the self signed certificate.

A) The Exchange server is accessible from NC
B) Configure Mail App is off
C) Configure server manually is on, the input field contains the exchange server name corresponding to the certificate name and I can browse the Exchange server using this very same name from de NC server command line (w3m https://exchsrv.domain.local works after accepting self-signed certificate)
D) I' ve tried different way of connecting, resulting in different errors in the NC logs :

Using "username" (not mentioning domain),
Using "domain.local\username",
Using "domain\username",
I've got the same error : 

`{"reqId":"aREDgaStEjmVQjOZnKTe","level":3,"time":"2023-11-16T10:53:41+01:00","remoteAddr":"X.X.X.X","user":"username","app":"PHP","method":"GET","url":"/index.php/apps/integration_ews/connect-alternate?account_id=username&account_secret=password&account_server=exchsrv.domain.local&flag=false","message":"Trying to access array offset on value of type bool at /var/www/nextcloud/apps/integration_ews/lib/Controller/UserConfigurationController.php#101","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0","version":"27.1.3.2","data":{"app":"PHP"}}`

Using "username@domain.local"
I've got :

`{"reqId":"rixUcbn4The3dkeTPOtc","level":3,"time":"2023-11-16T10:58:00+01:00","remoteAddr":"X.X.X.X","user":"username","app":"index","method":"GET","url":"/index.php/apps/integration_ews/connect-alternate?account_id=username%40domain.local&account_secret=password&account_server=exchsrv.domain.local&flag=false","message":"Unauthorized","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0","version":"27.1.3.2","exception":{"Exception":"RuntimeException","Message":"Unauthorized","Code":401,"Trace":[{"function":"__doRequest","class":"OCA\\EWS\\Components\\EWS\\EWSClient","type":"->"},{"file":"/var/www/nextcloud/apps/integration_ews/lib/Service/Remote/RemoteCommonService.php","line":224,"function":"__call","class":"SoapClient","type":"->"},{"file":"/var/www/nextcloud/apps/integration_ews/lib/Service/CoreService.php","line":351,"function":"fetchFolder","class":"OCA\\EWS\\Service\\Remote\\RemoteCommonService","type":"->"},{"file":"/var/www/nextcloud/apps/integration_ews/lib/Controller/UserConfigurationController.php","line":96,"function":"connectAccountAlternate","class":"OCA\\EWS\\Service\\CoreService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"ConnectAlternate","class":"OCA\\EWS\\Controller\\UserConfigurationController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1068,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/integration_ews/lib/Components/EWS/EWSClient.php","Line":298,"CustomMessage":"--"}}`

Using intentionally a false password gives me the same error.
Maybe there is a trick with UTF8 / non-UTF8 encoding ?
In order to connect the Nextcloud Mail App to this Exchange server, I had to modify the way the password is encoded : [see here](https://github.com/nextcloud/mail/issues/7660#issuecomment-1325138387)

**Comment by ksainc** [comment] 2023-11-16 13:46
Morning,

So your second attempt, using the "user@domail.local"  is the most promising, the error is "Message":"Unauthorized", meaning NC did actually connect to Exchange server, but was rejected on authorization.

The username and password are send directly from NC to Exchange, encoding should NOT be an issue, but it is possible. Its also possible that during the connection process the systems an negotiating NTML vs Basic Auth and there might be some difference in how Exchange 2007 handles NTLM. The app is setup to offer NTLM, Digest, and Basic auth, the server then chooses the auth method.

There are a few ways we can work on a fix,

A) Can you try a password without special characters
B) You seem pretty technical, so I can email you some instructions, and commands that you can test, using a test tool like Insomnia. To find the reason why the authentication is failing.
C) If the system is accessible externally, and you are comfortable with creating a, restricted test account (Limited to my IP and mail sending disabled)  for a couple of days, I can trouble shoot the problem on my end and fix any code that is needed.

You can email me at krupinski01@gmail.com, if you decided to proceed further.

Sebastian

**Comment by Mer0me** [comment] 2023-11-17 09:38
Ok, I was thinking the regular password without special chars have been tested but it wasn't.
I finally succeed with a regular password, but the security policy of our Active Directory imposes some special chars in password, so we have to found the correct way to connect theses account.
Unfortunately, I cannot give you access on this production environment. But I can help on testing some commands. I send you an email.

**Comment by delacosta456** [comment] 2023-11-17 18:32
hi all
As this issue (authentication)looks to be frequent in different scenario i am just thinking if for better readiness it will make sense to separate AutoDiscover issues related to each version of exchange.

May be either having it separated by Explicit title or  General Title+Labels

For example:

  - Explicit title:
    - (Exchange **2007**) AutoDiscover / Authenticate /etc 
    - (Exchange **2013**) AutoDiscover / Authenticate /etc
    - (Exchange **2019**) AutoDiscover / Authenticate /etc
    - _An dso on_
OR
  - General Title+Labels
    - **Ttile** : AutoDiscover / Authenticate issues 
    - **Labels** : Exchange , Ex::2007, AutoDiscover)
    - **Labels** : Exchange , Ex::2013, Authenticate )
    - **Labels** : Exchange , Ex::2019, Authenticate )
    - _And so on_

Will this make sense ?

Thanks

**Comment by ksainc** [comment] 2023-11-17 22:21
Hi delacosta456,

Are you talking about the error reporting templete?

Sebastian

**Comment by ksainc** [comment] 2023-11-28 03:28
Fixed in last commit

**Closed by ksainc** 2023-11-28 03:28 UTC

**Comment by Mer0me** [comment] 2023-12-01 10:56
I confirm that it's working now with special chars in password. (I applied the patch manually by editing EWSClient.php
